% Script generated by Brainstorm v3.1 (15-Jan-2014)

% Input files
sFiles = {...
    'Group_analysis/Attempt_Grasp_RT/results_wMNE_MEG_GRAD_MEG_MAG_KERNEL_140218_1510_NC01.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Run Matlab command
sFiles = bst_process(...
    'CallProcess', 'process_matlab_eval', ...
    sFiles, [], ...
    'matlab', ['% Available variables: Data, TimeVector' 10 '' 10 'Data = Data;' 10 ''], ...
    'overwrite', 0);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

