% Script generated by Brainstorm v3.1 (15-Jan-2014)

% Input files
sFiles = {...
    'Subject01_copy/@rawdbi05s01r05_tsss/data_0raw_dbi05s01r05_tsss.mat'};
RawFiles = {...
    '/home/foldes/Data/MEG/DBI05/S01/events_4BSTfromMatlab_dbi05s01r05_tsss_trans.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Events: Import from file
sFiles = bst_process(...
    'CallProcess', 'process_evt_import', ...
    sFiles, [], ...
    'evtfile', {RawFiles{1}, 'BST'});

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

