% Script generated by Brainstorm v3.1 (15-Jan-2014)

% Input files
sFiles = {...
    'link|Subject01_copy/1/results_wMNE_MEG_GRAD_MEG_MAG_KERNEL_140207_1350.mat|Subject01_copy/1/data_1_average_140207_1345.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Project on default anatomy
sFiles = bst_process(...
    'CallProcess', 'process_project_sources', ...
    sFiles, [], ...
    'source_abs', 0);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

