%BST_load_Tess;



sInput.SubjectName =    'Group_analysis';
sInput.Condition =      'Attempt_Grasp_RT';
TimeS =                 0.08; % 80ms after cue

ScoutInfo = process_SmartScout('Compute',sInput,'Threshold',...
    'NameDesign','[condition]_[DataThreshold]_[MaskScouts]',...
    'DataThreshold',0.7,...
    'TimeS',TimeS,...
    'MaskAtlas','Desikan-Killiany',...
    'MaskScouts','postcentral L');
