% Script generated by Brainstorm v3.1 (11-Jan-2013)

% Input files
FileNamesA = {...
    'NC01/@rawnc01s01r05_sss_trans/data_0raw_nc01s01r05_sss_trans.mat'};

% Start a new report
bst_report('Start', FileNamesA);

% Process: SSP EOG: blink
sFiles = bst_process(...
    'CallProcess', 'process_ssp_eog', ...
    FileNamesA, [], ...
    'eventname', 'blink', ...
    'sensortypes', 'MEG, MEG MAG, MEG GRAD');

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);

